// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"context"
	"errors"
	"template/infra/config"
	"template/infra/database/postgres"
	"template/infra/database/redis"
	"template/infra/httpserver"
	"template/infra/runtime"
)

// Injectors from wire.go:

func Wire(ctx context.Context, cfg *config.Config) (*runtime.App, func(), error) {
	addr := provideAddr(cfg)
	db, cleanup, err := postgres.NewPostgres(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	indicator := postgres.NewIndicator(db)
	client, cleanup2, err := redis.NewRedis(ctx, cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisIndicator := redis.NewIndicator(client)
	v := provideIndicators(indicator, redisIndicator)
	handler := httpserver.NewRouter(v)
	server := httpserver.NewServer(addr, handler, ctx)
	v2 := provideRunners(server)
	app := newApp(v2)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var ErrWireNotGenerated = errors.New("wire dependencies are not generated; run wire in infra/bootstrap")
